name: "Pull request checks"

on:
  pull_request:
    branches:
      - main

permissions:
  packages: write 
    
jobs:
  conventional_commits:
    name: Check if pull request title follows conventional commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract pull request title
        run: echo "${{ github.event.pull_request.title }}" > pull-request-title
      - name: Check conventional commit
        run: npx --yes git-conventional-commits commit-msg-hook pull-request-title

  test:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./package.json

      - name: Install Dependencies
        run: npm install

      - name: Audit Dependencies
        run: npm audit --audit-level=low

      - name: Run Tests
        run: npm test

  scan_image:
    name: Scan Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ github.repository }}
          tags: |
            type=ref,event=pr

      - name: Build
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: docker.io/${{ github.repository }}:pr-${{ github.event.number }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'