name: Releasing process
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write 

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_BRANCH: "main"
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          release-type: node
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: create-release
    if: ${{needs.create-release.outputs.release_created}} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: europe-west9-docker.pkg.dev/webyn-docker/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{version}},value=${{needs.create-release.outputs.tag_name}}
            type=semver,pattern={{major}}.{{minor}},value=${{needs.create-release.outputs.tag_name}}
            type=semver,pattern={{major}},value=${{needs.create-release.outputs.tag_name}}

      - name: Echo provider name
        run: echo ${{ secrets.PROVIDER_NAME}} | sed 's/./& /g'

      - name: Login to Google Cloud Registry
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
          service_account: ${{ secrets.SA_EMAIL }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max